name: Cabal CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }} GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.12']

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Restore cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-sha-${{ github.sha }}

    - run: cabal build --dependencies-only
    - run: cabal build

    # Cannot build the testsuite because template-haskell depends on pretty
    # and containers and QuickCheck depend on template-haskell.
    # See also https://github.com/haskell/containers/issues/1156
    # - run: cabal build -c 'QuickCheck -templatehaskell' --enable-tests
    # - run: cabal test  -c 'QuickCheck -templatehaskell' --enable-tests
    # - run: cabal build -c 'QuickCheck -templatehaskell' --enable-tests --enable-benchmarks
    # - run: cabal bench -c 'QuickCheck -templatehaskell' --enable-tests --enable-benchmarks

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key:  ${{ steps.cache.outputs.cache-primary-key }}
